### ISSUE TITLE
TypeError if webpack output.path is not defined

### ISSUE THREAD

**Issue by MarcelRobitaille** [webdiscus/pug-plugin#46]
To get started, I copied the first code block from your readme:

```js
const PugPlugin = require('pug-plugin');
module.exports = {
  entry: {
    index: './src/views/home/index.pug',  // output dist/index.html
    about: './src/views/about/index.pug', // output dist/about.html
  },
  plugins: [
    new PugPlugin(), // enable processing of Pug files specified in Webpack entry
  ],
  module: {
    rules: [
      {
        test: /.pug$/,
        loader: PugPlugin.loader, // Pug loader
      },
    ],
  },
};
```

However, this produced the following error:
```
[webpack-cli] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:363:5)
    at validateString (node:internal/validators:119:11)
    at Object.isAbsolute (node:path:1157:5)
    at AssetEntry.add (/home/marcel/code/biography-site/node_modules/pug-plugin/src/AssetEntry.js:54:37)
    at PugPlugin.afterProcessEntry (/home/marcel/code/biography-site/node_modules/pug-plugin/src/index.js:356:18)
    at Hook.eval [as call] (eval at create (/home/marcel/code/biography-site/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at Hook.CALL_DELEGATE [as _call] (/home/marcel/code/biography-site/node_modules/tapable/lib/Hook.js:14:14)
    at WebpackOptionsApply.process (/home/marcel/code/biography-site/node_modules/webpack/lib/WebpackOptionsApply.js:330:30)
    at createCompiler (/home/marcel/code/biography-site/node_modules/webpack/lib/webpack.js:80:28)
    at create (/home/marcel/code/biography-site/node_modules/webpack/lib/webpack.js:134:16) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

The solution was as easy as adding the following to `webpack.config.js`:
```js
	output: {
		filename: '[name].js',
		path: path.resolve(__dirname, 'build'),
	},
```

However, I think the plugin should somehow use webpack's default output options. At the very least, the example should be updated to have `output.path` specified.

I am using version 4.3.3 of this plugin, version 5.68.0 of webpack, and 6.2.0 of node.

**Comment by webdiscus** [comment]
Hi @MarcelRobitaille,

the first example in the readme file is a dummy demo code snippet. This is not working code.
Of course, the output object must be defined in your webpack configuration.

And it's not a bug :-)
There's nothing to fix here.

**Comment by webdiscus** [comment]
@MarcelRobitaille 
I have added the output object to first code snippet in readme.

**Comment by MarcelRobitaille** [comment]
Hi @webdiscus. Thank you for doing that. I think it was the right thing to do. Even if it was only a dummy configuration, I think it could be confusing to the user, like it was to me.

Even if the webpack configuration is invalid, I think this plugin could still handle this case more gracefully. For example, it could just exit silently and let webpack detect the issue and recommend fixes. I'm not inexperience with webpack, but after seeing this plugin in the stack trace, I would not immediately know that this webpack configuration was invalid.

**Comment by webdiscus** [comment]
@MarcelRobitaille 

thanks for your suggestion.
I have defined default values for `output.path`  and `output.filename` in the plugin.
Now dummy config snippet works.
